added logging

diff --git a/bin/procNewScans b/bin/procNewScans
--- a/bin/procNewScans
+++ b/bin/procNewScans
@@ -3,6 +3,18 @@
 # Line below locks the script so cannot be run simultaneously (i.e. to prevent conflicts)
 [ "${FLOCKER}" != "$0" ] && exec env FLOCKER="$0" flock -en "$0" "$0" "$@" || :
 
+CONFIG_DCM_RETRIEVE=$AUTOBIDS_DIR/cfg/dicom-retrieve.cfg
+#load in CONFIG_DCM_RETRIEVE file
+if [ -e $CONFIG_DCM_RETRIEVE  ]
+then
+	source $CONFIG_DCM_RETRIEVE
+else
+	echo "ERROR: $CONFIG_DCM_RETRIEVE not found!"
+	exit 1
+fi
+
+
+
 if [ "$#" -lt 1 ]
 then
     dates=$(date +'%Y%m%d')
@@ -10,7 +22,8 @@ else
     dates=$@
 fi
 
-
+mkdir -p $RETRIEVE_LOG_DIR
+LOG=$RETRIEVE_LOG_DIR/`date +%Y-%m-%d`.txt
 
 for date in $dates
 do
@@ -21,8 +34,8 @@ scratch_dir=/scratch/$USER/incoming_$RANDOM
 for study in `$AUTOBIDS_DIR/etc/getListStudies`
 do
  
- echo Retrieving dicoms for ${study}* on ${date}...
- getDicomTarballs \'${study}*\' \'${date}\' $scratch_dir
+ echo Retrieving dicoms for ${study}* on ${date}... | tee -a $LOG
+ getDicomTarballs \'${study}*\' \'${date}\' $scratch_dir | tee -a $LOG
 
 done
 
@@ -33,10 +46,10 @@ then
 for tar in `ls $scratch_dir/*.tar`
 do
   tar_name=${tar##*/}
-  if [ ! $(grep ${tar_name} $AUTOBIDS_DIR/var/downloaded_tar.dat) ]
+  if [ ! $(grep ${tar_name} $DOWNLOADED_TAR_LIST) ]
   then
-	echo $tar_name >> $AUTOBIDS_DIR/var/downloaded_tar.dat
-	autobidsProcess $tar
+	echo $tar_name >> $DOWNLOADED_TAR_LIST
+	autobidsProcess $tar 
   fi
 
 done
