remove ability to create default study_cfg

diff --git a/etc/getStudyCfg b/etc/getStudyCfg
--- a/etc/getStudyCfg
+++ b/etc/getStudyCfg
@@ -51,23 +51,9 @@ done
 if [ ! -e $autocfg ]
 then
 
-	default=$AUTOBIDS_STUDY_CFG_DIR/default
-	autocfg=$AUTOBIDS_STUDY_CFG_DIR/${pi}_${study}
 	
-	if [ -e $default ]  
-	then
-	 	echo "Study config not found, creating $autocfg from default" >&2 
-		cp -v $default $autocfg >&2
-	else
-	 	echo "Study config not found, and default does not exist: $default" >&2
-		exit 1
-	fi
-
-	if [ ! -e $autocfg ]
-	then
-		echo "ERROR in $0: config could not be created: $autocfg (check write-permissions)" >&2
-		exit 1
-	fi
+	echo "ERROR in $0: config could not be found: $autocfg (check write-permissions)" >&2
+	exit 1
 fi
 
 echo $autocfg
